# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xci
# IP: The module: 'bse_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xci
# IP: The module: 'bse_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcrye/Downloads/v2/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
