# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.cache/wt [current_project]
set_property parent.project_path C:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/mcrye/AppData/Roaming/Xilinx/Vivado/bse_pynq_z1/solution1/impl/ip
  c:/Users/AppData/Roaming/Xilinx/Vivado/byte_statistics_engine/solution1/impl/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/hdl/bse_wrapper.v
add_files C:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/bse.bd
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_byte_statistics_engi_0_0/constraints/byte_statistics_engine_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_xbar_0/bse_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_1/bd_c34f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_1/bd_c34f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_2/bd_c34f_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_3/bd_c34f_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_4/bd_c34f_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_5/bd_c34f_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_6/bd_c34f_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_10/bd_c34f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_11/bd_c34f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_12/bd_c34f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_16/bd_c34f_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_17/bd_c34f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_18/bd_c34f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_19/bd_c34f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_20/bd_c34f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_21/bd_c34f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_22/bd_c34f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_23/bd_c34f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_24/bd_c34f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_smartconnect_0_0/bd_0/ip/ip_25/bd_c34f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_axi_dma_0_0/bse_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_axi_dma_0_0/bse_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_axi_dma_0_0/bse_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_processing_system7_0_0/bse_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/ip/bse_auto_pc_0/bse_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mcrye/Downloads/bladei_bse_pynq_z1/bladei_bse_pynq_z1.srcs/sources_1/bd/bse/bse_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bse_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bse_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bse_wrapper_utilization_synth.rpt -pb bse_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
