# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bse/bse.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse || ORIG_REF_NAME==bse} -quiet] -quiet

# IP: bd/bse/ip/bse_byte_statistics_engi_0_0/bse_byte_statistics_engi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_byte_statistics_engi_0_0 || ORIG_REF_NAME==bse_byte_statistics_engi_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_xbar_0/bse_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_xbar_0 || ORIG_REF_NAME==bse_xbar_0} -quiet] -quiet

# IP: bd/bse/ip/bse_axi_interconnect_0_0/bse_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_axi_interconnect_0_0 || ORIG_REF_NAME==bse_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_proc_sys_reset_0_0/bse_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_proc_sys_reset_0_0 || ORIG_REF_NAME==bse_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_smartconnect_0_0/bse_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_smartconnect_0_0 || ORIG_REF_NAME==bse_smartconnect_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_axi_dma_0_0/bse_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_axi_dma_0_0 || ORIG_REF_NAME==bse_axi_dma_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_processing_system7_0_0/bse_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_processing_system7_0_0 || ORIG_REF_NAME==bse_processing_system7_0_0} -quiet] -quiet

# IP: bd/bse/ip/bse_auto_pc_0/bse_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bse_auto_pc_0 || ORIG_REF_NAME==bse_auto_pc_0} -quiet] -quiet

# XDC: bd/bse/bse_ooc.xdc
