# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mcrye/Downloads/bladei_bse_zcu104/bladei_bse_zcu104.srcs/sources_1/bd/bse/ip/bse_byte_statistics_engi_0_0/bse_byte_statistics_engi_0_0.xci
# IP: The module: 'bse_byte_statistics_engi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcrye/Downloads/bladei_bse_zcu104/bladei_bse_zcu104.srcs/sources_1/bd/bse/ip/bse_byte_statistics_engi_0_0/constraints/byte_statistics_engine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_byte_statistics_engi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/mcrye/Downloads/bladei_bse_zcu104/bladei_bse_zcu104.srcs/sources_1/bd/bse/ip/bse_byte_statistics_engi_0_0/bse_byte_statistics_engi_0_0.xci
# IP: The module: 'bse_byte_statistics_engi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcrye/Downloads/bladei_bse_zcu104/bladei_bse_zcu104.srcs/sources_1/bd/bse/ip/bse_byte_statistics_engi_0_0/constraints/byte_statistics_engine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bse_byte_statistics_engi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
